### ISSUE TITLE
h.default is not a constructor

### ISSUE THREAD

**Issue by wangqing6** [agilgur5/react-signature-canvas#51] opened 2020-07-08 03:10 UTC
"react": "^16.4.2",
```
index.js:1 Uncaught TypeError: h.default is not a constructor
    at t.value (index.js:1)
    at commitLifeCycles (react-dom.development.js:19814)
    at commitLayoutEffects (react-dom.development.js:22803)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
    at invokeGuardedCallback (react-dom.development.js:292)
    at commitRootImpl (react-dom.development.js:22541)
    at unstable_runWithPriority (scheduler.development.js:653)
    at runWithPriority$1 (react-dom.development.js:11039)
    at commitRoot (react-dom.development.js:22381)
    at finishSyncRender (react-dom.development.js:21807)
    at performSyncWorkOnRoot (react-dom.development.js:21793)
    at react-dom.development.js:11089
    at unstable_runWithPriority (scheduler.development.js:653)
    at runWithPriority$1 (react-dom.development.js:11039)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11084)
    at flushSyncCallbackQueue (react-dom.development.js:11072)
    at discreteUpdates$1 (react-dom.development.js:21893)
    at discreteUpdates (react-dom.development.js:806)
    at dispatchDiscreteEvent (react-dom.development.js:4168)
```

**Comment by agilgur5** [comment] 2020-07-08 14:55
Duplicate of #36 . Like that issue, you need to provide a reproduction, and not just an error message.

**Closed by agilgur5** 2020-07-08 14:55 UTC
