### ISSUE TITLE
Stroke offset with Next.js prod build

### ISSUE THREAD

**Issue by ElTimuro** [agilgur5/react-signature-canvas#96] opened 2023-02-18 16:49 UTC
Hey,

I'm getting a weird offset on the created stroke, but only with a production build using react/ nextjs ('next build'). It works fine in dev using 'next dev'. Any ideas why? It does not seem to be layouting-related since it works locally, even on touch.

![image](https://user-images.githubusercontent.com/1309312/219877765-34750aca-ddbd-4997-bada-fa49ce2c732f.png)
![New Project](https://user-images.githubusercontent.com/1309312/219877781-21e94518-5c36-4dc8-b52b-ead733e37304.gif)

Setup is quite simple:
```
          <SignatureCanvas
            ref={(ref) => {
              signCanvas = ref;
            }}
            canvasProps={{
              className:
                "sigCanvas border-b b-2 border-slate w-full h-full mb-3",
            }}
            clearOnResize={true}
          />
```

Am I not seeing something? Happy to provide working code if it helps.

**Comment by agilgur5** [comment] 2023-02-18 20:02
Duplicate of #95

**Closed by agilgur5** 2023-02-18 20:02 UTC

**Comment by ElTimuro** [comment] 2023-02-18 20:42
Thanks. My bad, should have looked better 🙏
