### ISSUE TITLE
Cannot import after adding ts definition

### ISSUE THREAD

**Issue by alkafaiz** [agilgur5/react-signature-canvas#38] opened 2019-12-23 05:24 UTC
Hi there, I'm facing this error where ts definitions is not found. I have followed the step in #21 but still not working. This error appears in the console.

```
Uncaught TypeError: h.default is not a constructor
    at t.value (index.js:1)
    at commitLifeCycles (react-dom.development.js:22101)
    at commitLayoutEffects (react-dom.development.js:25344)
    at HTMLUnknownElement.callCallback (react-dom.development.js:336)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:385)
    at invokeGuardedCallback (react-dom.development.js:440)
    at commitRootImpl (react-dom.development.js:25082)
    at unstable_runWithPriority (scheduler.development.js:697)
    at runWithPriority$2 (react-dom.development.js:12149)
    at commitRoot (react-dom.development.js:24922)
    at finishSyncRender (react-dom.development.js:24329)
    at performSyncWorkOnRoot (react-dom.development.js:24307)
    at react-dom.development.js:12199
    at unstable_runWithPriority (scheduler.development.js:697)
    at runWithPriority$2 (react-dom.development.js:12149)
    at flushSyncCallbackQueueImpl (react-dom.development.js:12194)
    at flushSyncCallbackQueue (react-dom.development.js:12182)
    at discreteUpdates$1 (react-dom.development.js:24423)
    at discreteUpdates (react-dom.development.js:1438)
    at dispatchDiscreteEvent (react-dom.development.js:5881)
```
```
Uncaught TypeError: Cannot read property 'off' of null
    at t.r.off (index.js:1)
    at t.value (index.js:1)
    at callComponentWillUnmountWithTimer (react-dom.development.js:21896)
    at HTMLUnknownElement.callCallback (react-dom.development.js:336)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:385)
    at invokeGuardedCallback (react-dom.development.js:440)
    at safelyCallComponentWillUnmount (react-dom.development.js:21903)
    at commitUnmount (react-dom.development.js:22392)
    at commitNestedUnmounts (react-dom.development.js:22486)
    at unmountHostComponents (react-dom.development.js:22810)
    at commitUnmount (react-dom.development.js:22429)
    at commitNestedUnmounts (react-dom.development.js:22486)
    at unmountHostComponents (react-dom.development.js:22810)
    at commitDeletion (react-dom.development.js:22896)
    at commitMutationEffects (react-dom.development.js:25323)
    at HTMLUnknownElement.callCallback (react-dom.development.js:336)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:385)
    at invokeGuardedCallback (react-dom.development.js:440)
    at commitRootImpl (react-dom.development.js:25050)
    at unstable_runWithPriority (scheduler.development.js:697)
    at runWithPriority$2 (react-dom.development.js:12149)
    at commitRoot (react-dom.development.js:24922)
    at finishSyncRender (react-dom.development.js:24329)
    at performSyncWorkOnRoot (react-dom.development.js:24307)
    at react-dom.development.js:12199
    at unstable_runWithPriority (scheduler.development.js:697)
    at runWithPriority$2 (react-dom.development.js:12149)
    at flushSyncCallbackQueueImpl (react-dom.development.js:12194)
    at flushSyncCallbackQueue (react-dom.development.js:12182)
    at discreteUpdates$1 (react-dom.development.js:24423)
    at discreteUpdates (react-dom.development.js:1438)
    at dispatchDiscreteEvent (react-dom.development.js:5881)
```
where index.js refers to index in build folder.

**Comment by agilgur5** [comment] 2019-12-23 05:57
TypeScript is not officially supported at this time. As I said before, please read the comments on #25. I cannot comment or help with the type definitions of #21 given that they are unofficial and unsupported. You can seek help from users of that method on that issue. Otherwise, you can wait for official TypeScript support to make it into the library (please see https://github.com/agilgur5/react-signature-canvas/pull/25#issuecomment-562713553 for some of that progress, will create some PRs in the near future)

<hr>

With regard to the error you received, this is potentially a duplicate of #36. Like that issue, I am unable to reproduce this. All of the examples work fine, including the [CodeSandbox playground](https://codesandbox.io/s/github/agilgur5/react-signature-canvas/tree/cra-example) and [live demo](https://agilgur5.github.io/react-signature-canvas/)

You'll have to provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) or demo displaying this behavior, such as:

- a CodeSandbox example (or equivalent) or
- a screencapture of it at the demo site and the steps you took to reproduce it or
- a failing test case. All tests currently pass.

Can re-open and analyze the issue once I can reproduce it.

<hr>

Will have to create an issue template soon as most of the recent issues have failed to include reproductions.

**Closed by agilgur5** 2019-12-23 05:57 UTC

**Comment by agilgur5** [comment] 2025-02-15 04:57
> Otherwise, you can wait for official TypeScript support to make it into the library

[`v1.1.0-alpha.1`](https://github.com/agilgur5/react-signature-canvas/releases/tag/v1.1.0-alpha.1) has been released as the first official native TS release
