### ISSUE TITLE
Resize causes de-sync when clearOnResize=false

### ISSUE THREAD

**Issue by ishika1727** [agilgur5/react-signature-canvas#57] opened 2020-09-23 17:41 UTC
How to handle high DPI screens using this package. While using this package in my code, when I resize it to mobile view is goes like this gif. Please suggest appropriate way to rectify this. @agilgur5 

![ey](https://user-images.githubusercontent.com/42978414/94049045-040b8c00-fdf2-11ea-8830-5b0a88fa7635.gif)

**Comment by agilgur5** [comment] 2020-09-25 15:02
If you're experience a de-sync after a resize, that's because you've set `clearOnResize={false}`, meaning you've opted out of the internal resize handling. The de-sync is unrelated to high DPI or not, though that may increase the scale of de-sync.

This is a duplicate of #43

**Closed by agilgur5** 2020-09-25 15:02 UTC
