### ISSUE TITLE
is there a way to set an existing value?

### ISSUE THREAD

**Issue by kennblvnp** [agilgur5/react-signature-canvas#55] opened 2020-07-27 08:23 UTC
like for example:

`<SignatureCanvas value={signature.toDataURL('image/png')} />`

**Comment by agilgur5** [comment] 2020-07-31 19:56
Duplicate of #53 .

Like your other issue #54, I'm not sure what the use-case is for this, this isn't something you'd normally want to do as you wouldn't normally let people _edit_ their signature.

**Closed by agilgur5** 2020-07-31 19:56 UTC
