### ISSUE TITLE
`TypeError: undefined is not an object (evaluating 'this._data[this._data.length-1].push')`

### ISSUE THREAD

**Issue by chetankaleidoscope** [agilgur5/react-signature-canvas#90] opened 2022-07-01 07:03 UTC
Sentry Issue: [DIG-PRODUCTION-6V](https://sentry.io/organizations/mykaleidoscope/issues/2761675828/?referrer=jira_integration)

![image](https://user-images.githubusercontent.com/98539142/176842108-970e1372-4858-489f-b5a3-6b4b42c73b1e.png)

Please fix this issue.

**Comment by agilgur5** [comment] 2022-07-01 07:18
Duplicate of https://github.com/szimek/signature_pad/issues/329 which is upstream in `signature_pad`, not here. There is no such code in this tiny codebase.

A PR also already exists to fix this by updating to v4 in #68 . Per comments there, it is a _very_ breaking upgrade that has not been handled yet.

> Please fix this issue.

Please be respectful of others. Especially volunteer maintainers and their volunteer time and expertise.
Triply so if you have not searched this issue yourself.

**Closed by agilgur5** 2022-07-01 07:18 UTC
Labels: kind: bug, solution: duplicate, scope: upstream
