### ISSUE TITLE
isEmpty is not working as expected

### ISSUE THREAD

**Issue by ecaven** [agilgur5/react-signature-canvas#16] opened 2018-01-18 12:02 UTC
isEmpty is set as true when canvas is clicked. 

This causes troubles in cases when there is already something drawn on to the canvas and the last strokes length is less than 2.

So isEmpty shouldn't be set as true when there is already some content on the canvas.

**Comment by agilgur5** [comment] 2018-01-18 22:59
ah yep, that's a good catch. seems like this was fixed upstream in `signature_pad` as part of https://github.com/szimek/signature_pad/pull/208 . Setting `isEmpty = true` needs to be moved out of `_reset` and into `fromDataURL` and `clear` since `_reset` is also called during `_strokeBegin`

**Comment by agilgur5** [comment] 2018-02-05 02:42
Fixed in v0.2.4 as https://github.com/agilgur5/react-signature-canvas/commit/22d8019d3e2ccd56096585cb455404f758e458d3 and v0.1.10 as https://github.com/agilgur5/react-signature-canvas/commit/923f62b697f9a9cc3fb193449b4d42a07acdb673 .

This is effectively the same as https://github.com/szimek/signature_pad/pull/208/commits/b446b2422a2b3d519a0e6522d18ea113b7da0741 . Moving forward, will be working on #17 so certain bugs like this one would be addressed upstream

**Closed by agilgur5** 2018-02-05 02:42 UTC

**Comment by ctrlaltdylan** [comment] 2021-03-13 20:35
Sorry to both @agilgur5  but it seems like the latest tag `v1.0.3` does not include the fix for the `isEmpty` bug. I downgraded to `v0.1.11` and the `isEmpty` worked as expected.

**Comment by agilgur5** [comment] 2021-03-13 23:06
@ctrlaltdylan per the above 3 year old comment, #17 was implemented by #20, and as such the v1.x line wraps upstream `signature_pad`. Per that comment and the one before it, it was implemented in `signature_pad` [v1.6.0](https://github.com/szimek/signature_pad/compare/v1.5.3...v1.6.0) 4 years ago. `react-signature-canvas` uses a much newer version than that, [v2.3.2](https://github.com/agilgur5/react-signature-canvas/blob/d449c18b5d3b7e3bda22bdafcc7e9ddba9e51cd7/package.json#L53).

As of #33 and #34, `react-signature-canvas` also has 100% test coverage, and there actually are some [tests for `isEmpty`](https://github.com/agilgur5/react-signature-canvas/blob/d449c18b5d3b7e3bda22bdafcc7e9ddba9e51cd7/src/index.spec.js#L96), despite that being upstream, and those tests pass (and there is CI as well).

If you think you've found a bug, that would be upstream in `signature_pad` and not here. But to report a bug, you should really provide a minimal reproduction and/or a failing test. I would recommend filing an issue with a reproduction upstream, and not necro'ing a 3 year old issue that references a fairly different version of the codebase.

**Comment by ctrlaltdylan** [comment] 2021-03-14 01:09
Hi @agilgur5 thanks for the really quick response.

Here's a codesandbox showing the bug: https://codesandbox.io/s/react-signature-canvas-example-forked-6zz14?file=/package.json

To give more context I upgraded to `v16.x` of React. Possibly could have something to do with it.

Just meant to leave a quick solution for others googling around like myself in a topic that had a similar phrase that describes the bug.

Once I have more time I'll do a deeper dive, just have a deadline at the moment.

Thanks again!

**Comment by agilgur5** [comment] 2021-03-14 01:26
@ctrlaltdylan thanks for the repro. That looks like a bug in your code / usage of React. The canvas is basically an uncontrolled component, so it is not generally updating any state when you draw on it, so the text for `empty` will not update on it's own. You'd need to add a callback or something if you want it to automatically refresh and update.

But again, this is upstream behavior and has a test here.

**Comment by ctrlaltdylan** [comment] 2021-03-14 01:35
@agilgur5 ah I see!

So it sounds like I'm better off using the `onBegin` and `onEnd` as callbacks for state.

```
const [isSigned, setIsSigned] = useState(false);

<SignaturePad
   ...other important props
   onEnd={() => { setIsSigned(true} }
/>

// intention is to disable the button until some sort of signature is available
<Button disabled={!isSigned}>
   Submit
</Button>

```

**Comment by ctrlaltdylan** [comment] 2021-03-14 01:39
Sorry, didn't mean to cause any disruption on your issues flow! Great library, it was so easy to get up and running. If you'd like I can PR a basic hook example. Might be helpful for others.

**Comment by agilgur5** [comment] 2021-03-14 02:05
> So it sounds like I'm better off using the `onBegin` and `onEnd` as callbacks for state.

That's the idea, but there's an edge case you're missing there too -- if you `clear` the canvas after starting, it'll incorrectly allow you to submit. So you'd need to `setIsSigned(false)` at least on a `clear` call as well.

There'd still be a second edge case after that though, which is that window resizes will cause the canvas to clear. If your canvas is of fixed size, you can set `clearOnResize={false}`. If it's not fixed size though, setting that prop comes with some caveats in that the native canvas element can de-sync or clear itself on resize (that's browser behavior, not library behavior, `clearOnResize` by default fixes any de-sync). But that's the topic of #43.

There's potentially a third edge case if you ever use `fromData*` as well (since you'd be setting without drawing).

> If you'd like I can PR a basic hook example. Might be helpful for others.

Sure. Folks have submitted some very complex hooks examples that are not great for newbies, so a basic one would be welcome.

Full transparency though that It'll be a while before I can actually merge it as I still need to create a Storybook in order to show multiple examples seamlessly, so that'll be backlogged until then similar to the leftover example in #9. But can still be searched / referenced in the meantime and I'll make sure to give credit to anything that's merged at a later date into a Storybook.

**Comment by agilgur5** [comment] 2021-03-14 02:14
Ah I remembered how I had `disabled` states. It was more similar to a debounce flow, basically on the `button`'s `onClick`, you'd check `isEmpty()` and only proceed if `true`. Not optimal UX of course as the button is still enabled (but does nothing if no drawing), but it works for a quick solution.

**Comment by ctrlaltdylan** [comment] 2021-04-01 11:50
@agilgur5 yup that's the conclusion I came to as well. Finally catching a break from "real work" and I'll get back to this doc example. Should be a simple PR. Thanks again you're an OSS hero for keeping the best e-signature capture library fork running for this long.
