### ISSUE TITLE
Cannot get SVG data url after `getTrimmedCanvas()`

### ISSUE THREAD

**Issue by Szorcu** [agilgur5/react-signature-canvas#101] opened 2023-10-16 15:18 UTC
Hi,
 
I have a problem with the `getTrimmedCanvas()` function. After calling it, calling `toDataUrl('image/svg+xml')` on the trimmed canvas does not work as expected.

During debugging, I noticed that this is because the function returns `HTMLCanvasElement` instead of `ReactSignatureCanvas` or `SignaturePad`. The short way to put it is that calling the `getTrimmedCanvas()` function involves losing access to all the functions/variables provided by `ReactSignatureCanvas`.

**Comment by agilgur5** [comment] 2023-10-16 21:24
Duplicate of #49

Yes, this is expected behavior. `getTrimmedCanvas()` is not built-in to `signature_pad` so there is no way for it to return a `signature_pad`. The typings and docs do explicitly say that it returns a native `canvas` element.

Per the docs, `getTrimmedCanvas` uses a tiny library [`trim-canvas`](https://github.com/agilgur5/trim-canvas) under-the-hood (which is suggested in the [`signature_pad` docs](https://github.com/szimek/signature_pad#removing-empty-space-around-a-signature) that operates on a native `canvas` element.

I did consider [building in support for SVG trimming](https://github.com/szimek/signature_pad/issues/49#issuecomment-712411003) by wrapper another tiny `trim-svg` library (a counterpart to `trim-canvas`), but the API would be a bit clunky as it wouldn't be built-in to `signature_pad` either. 

`trim-canvas` (and `trim-svg`, if it were to exist) is meant to be used as the final operation after the usage of the `canvas` is completed to turn into a PNG data URL.

**Closed by agilgur5** 2023-10-16 21:24 UTC
Labels: kind: support

**Comment by agilgur5** [comment] 2023-10-17 14:19
> ```ts
> return new SignaturePad(trimmedCanvas, this._excludeOurProps())
> ```

A `canvas` is pure raster data (basically just pixels), there is no point data that is passed to `signature_pad` in that case. You won't be able to convert that to an SVG as there is no point data associated with it. You can try it yourself to view the behavior as well.

You can see `signature_pad`'s [`constructor` here](https://github.com/szimek/signature_pad/blob/4cd5e544b32eaaa146cf9ef3836f41e1b2f73fc1/src/signature_pad.ts#L81); no point data is extracted from the `canvas`.
