### ISSUE TITLE
Canvas resizes and then breaks

### ISSUE THREAD

**Issue by FrancoSabadini** [agilgur5/react-signature-canvas#47] opened 2020-03-27 02:55 UTC
Hi,

I'm trying to use your library but I'm having 2 issues:

1. The line appears to the right of where the mouse is when adding a signature.

2. When resizing the browser window, the canvas takes over the whole screen and then breaks.

Is there any way to fix these issues?

**Comment by agilgur5** [comment] 2020-03-27 03:18
You did not provide any reproduction so it is difficult to really say much.

> 1. The line appears to the right of where the mouse is when adding a signature.

Sounds like a de-sync issue meaning you've set `clearOnResize` to `false` and are not properly handling the resize. Duplicate of #43, see that for more information

> 2\. When resizing the browser window, the canvas takes over the whole screen and then breaks.

This component's resize behavior is entirely based on the width and height it's set to; if a dimension isn't fixed then it becomes responsive and resizes proportionally. Sounds like your dimensions aren't fixed and don't work for the screen sizes you're targeting.
If you're combining that with `clearOnResize=false`, then by "breaks", you're probably experiencing a significant de-sync given the scope of the resize and just not seeing where things get drawn. Please refer to #43

**Closed by agilgur5** 2020-03-27 03:18 UTC

**Comment by francos** [comment] 2020-04-02 04:26
Thanks for the quick answer and sorry for the late response @agilgur5.

In the end, I could fix this by setting a width of `100%` and a specific `height` in `px` to the `canvas` through the `canvasProps`.
